name: Terraform sns_sqs_start

on:
 workflow_dispatch:
 #push:
  #  branches:
   #   - main
    #  - develop
      

env:
  #TF_VERSION: "1.6.0"
  TF_VERSION: "1.7.5"
  AWS_REGION: "us-east-1"
  TF_WORKING_DIR: "./sns_sqs"

jobs:
  terraform:
    name: Terraform CI/CD
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}  
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Gerar Terraform
        run: cd sns_sqs && terraform init && terraform plan -out=tfplan && terraform apply -auto-approve  tfplan

      - name: Verificar existência do arquivo Terraform State
        run: ls -lah

      - name: Salvar Estado Terraform
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          #path:  ${{ env.TF_WORKING_DIR }}/terraform.tfstate
          path:  ./sns_sqs/terraform.tfstate          

      - name: Buscar arquivo terraform.tfstate
        run: find . -name "terraform.tfstate"          
